// GENERATED by scripts/gen_deepsuite_tokens.py — DO NOT EDIT.
// Source: reference/.../ui-theme/src/styles/{design-platform,base}.css
// Regenerate: python3 scripts/gen_deepsuite_tokens.py
library;

import "package:flutter/painting.dart" show Color;

/// Raw deepsuite palette (theme-independent statics).
final class DeepSuiteStatic {
  const DeepSuiteStatic._();
  static const Color amber100 = Color(0xfffef5e7);
  static const Color amber400 = Color(0xfff7ad31);
  static const Color amber500 = Color(0xfff59e0b);
  static const Color amber600 = Color(0xffdd8629);
  static const Color amber900 = Color(0xff27241f);
  static const Color blue100 = Color(0xffdbeafe);
  static const Color blue300 = Color(0xff93c5fd);
  static const Color blue400 = Color(0xff60a5fa);
  static const Color blue450 = Color(0xff4d93f8);
  static const Color blue50 = Color(0xffeff6ff);
  static const Color blue500 = Color(0xff3b82f6);
  static const Color blue50P = Color(0xffeaf3ff);
  static const Color blue600 = Color(0xff2563eb);
  static const Color blue75 = Color(0xffe5f0ff);
  static const Color blue800 = Color(0xff1e40af);
  static const Color blue900 = Color(0xff0e3074);
  static const Color blue950 = Color(0xff172554);
  static const Color deepseek100 = Color(0xffe4edfd);
  static const Color deepseek200 = Color(0xffd3e2ff);
  static const Color deepseek300 = Color(0xffb7c8fe);
  static const Color deepseek400 = Color(0xff679efe);
  static const Color deepseek450 = Color(0xff5686fe);
  static const Color deepseek50 = Color(0xffedf3fe);
  static const Color deepseek500 = Color(0xff4176e6);
  static const Color deepseek600 = Color(0xff4868b2);
  static const Color deepseek700 = Color(0xff2f4c8f);
  static const Color deepseek800 = Color(0xff34415b);
  static const Color deepseek900 = Color(0xff283142);
  static const Color green100 = Color(0xffe6faed);
  static const Color green400 = Color(0xff4ed17e);
  static const Color green500 = Color(0xff22c55e);
  static const Color green900 = Color(0xff233c2c);
  static const Color neutral00 = Color(0xffffffff);
  static const Color neutral100 = Color(0xfff5f5f5);
  static const Color neutral1000 = Color(0xff000000);
  static const Color neutral150 = Color(0xffededed);
  static const Color neutral200 = Color(0xffe5e5e5);
  static const Color neutral250 = Color(0xffdcdcdc);
  static const Color neutral300 = Color(0xffd4d4d4);
  static const Color neutral400 = Color(0xffa2a4a6);
  static const Color neutral50 = Color(0xfffafafa);
  static const Color neutral500 = Color(0xff7f8287);
  static const Color neutral550 = Color(0xff65676b);
  static const Color neutral600 = Color(0xff545557);
  static const Color neutral700 = Color(0xff3c3c3d);
  static const Color neutral800 = Color(0xff292929);
  static const Color neutral850 = Color(0xff212123);
  static const Color neutral900 = Color(0xff0f0f0f);
  static const Color neutralBluish00 = Color(0xffffffff);
  static const Color neutralBluish100 = Color(0xffebeef2);
  static const Color neutralBluish1000 = Color(0xff0f1115);
  static const Color neutralBluish150 = Color(0xffe9ecf2);
  static const Color neutralBluish200 = Color(0xffe1e5ee);
  static const Color neutralBluish300 = Color(0xffcfd3d6);
  static const Color neutralBluish400 = Color(0xffadb2b8);
  static const Color neutralBluish50 = Color(0xfff9fafb);
  static const Color neutralBluish500 = Color(0xff979da6);
  static const Color neutralBluish600 = Color(0xff81858c);
  static const Color neutralBluish700 = Color(0xff61666b);
  static const Color neutralBluish75 = Color(0xfff1f3f5);
  static const Color neutralBluish750 = Color(0xff43454a);
  static const Color neutralBluish800 = Color(0xff353638);
  static const Color neutralBluish850 = Color(0xff2c2c2e);
  static const Color neutralBluish875 = Color(0xff232324);
  static const Color neutralBluish900 = Color(0xff1b1b1c);
  static const Color neutralBluish950 = Color(0xff151517);
  static const Color red100 = Color(0xfffee2e2);
  static const Color red400 = Color(0xfff25a5a);
  static const Color red50 = Color(0xfffef2f2);
  static const Color red500 = Color(0xffef4444);
  static const Color red600 = Color(0xffec1313);
  static const Color red900 = Color(0xff570c0c);
}

/// Semantic `Light` aliases resolved to concrete colors.
final class DeepSuiteLight {
  const DeepSuiteLight._();
  /// --dsw-alias-bg-base
  static const Color aliasBgBase = DeepSuiteStatic.neutralBluish00;
  /// --dsw-alias-bg-layer-1
  static const Color aliasBgLayer1 = DeepSuiteStatic.neutralBluish00;
  /// --dsw-alias-bg-layer-2
  static const Color aliasBgLayer2 = DeepSuiteStatic.neutralBluish00;
  /// --dsw-alias-bg-layer-3
  static const Color aliasBgLayer3 = DeepSuiteStatic.neutralBluish00;
  /// --dsw-alias-bg-mask-1
  static const Color aliasBgMask1 = Color(0x3d000000);
  /// --dsw-alias-bg-mask-2
  static const Color aliasBgMask2 = Color(0x1f000000);
  /// --dsw-alias-bg-mask-3
  static const Color aliasBgMask3 = Color(0x7a000000);
  /// --dsw-alias-bg-mask-drop
  static const Color aliasBgMaskDrop = Color(0xb2ffffff);
  /// --dsw-alias-bg-mask-photo
  static const Color aliasBgMaskPhoto = Color(0xe0000000);
  /// --dsw-alias-bg-module-platform
  static const Color aliasBgModulePlatform = Color(0xfff5f6f7);
  /// --dsw-alias-bg-multi-select
  static const Color aliasBgMultiSelect = Color(0xfff5f6f7);
  /// --dsw-alias-bg-overlay
  static const Color aliasBgOverlay = DeepSuiteStatic.neutralBluish150;
  /// --dsw-alias-bg-skeleton
  static const Color aliasBgSkeleton = Color(0x0a000000);
  /// --dsw-alias-border-inverted
  static const Color aliasBorderInverted = Color(0x00000000);
  /// --dsw-alias-border-inverted2
  static const Color aliasBorderInverted2 = Color(0x00000000);
  /// --dsw-alias-border-l1
  static const Color aliasBorderL1 = Color(0x0a000000);
  /// --dsw-alias-border-l2
  static const Color aliasBorderL2 = Color(0x1a000000);
  /// --dsw-alias-border-l2-darkmode-thin
  static const Color aliasBorderL2DarkmodeThin = Color(0x1a000000);
  /// --dsw-alias-border-l3
  static const Color aliasBorderL3 = Color(0x1f000000);
  /// --dsw-alias-border-l4
  static const Color aliasBorderL4 = Color(0x29000000);
  /// --dsw-alias-brand-primary
  static const Color aliasBrandPrimary = DeepSuiteStatic.neutralBluish1000;
  /// --dsw-alias-brand-primary-invert
  static const Color aliasBrandPrimaryInvert = DeepSuiteStatic.neutralBluish1000;
  /// --dsw-alias-brand-primary-new-colorprimary-new-color
  static const Color aliasBrandPrimaryNewColorprimaryNewColor = Color(0xff4176e6);
  /// --dsw-alias-brand-text
  static const Color aliasBrandText = DeepSuiteStatic.neutralBluish1000;
  /// --dsw-alias-button-contrast-fill
  static const Color aliasButtonContrastFill = DeepSuiteStatic.neutralBluish700;
  /// --dsw-alias-button-elevated-fill
  static const Color aliasButtonElevatedFill = DeepSuiteStatic.neutralBluish00;
  /// --dsw-alias-button-floating-fill
  static const Color aliasButtonFloatingFill = DeepSuiteStatic.neutralBluish00;
  /// --dsw-alias-button-floating-hover
  static const Color aliasButtonFloatingHover = DeepSuiteStatic.neutralBluish75;
  /// --dsw-alias-button-ghost-active-border
  static const Color aliasButtonGhostActiveBorder = DeepSuiteStatic.neutralBluish500;
  /// --dsw-alias-button-ghost-active-fill
  static const Color aliasButtonGhostActiveFill = DeepSuiteStatic.neutralBluish100;
  /// --dsw-alias-button-ghost-active-hover
  static const Color aliasButtonGhostActiveHover = DeepSuiteStatic.neutralBluish150;
  /// --dsw-alias-button-info-fill
  static const Color aliasButtonInfoFill = DeepSuiteStatic.deepseek500;
  /// --dsw-alias-button-info-hover
  static const Color aliasButtonInfoHover = DeepSuiteStatic.deepseek400;
  /// --dsw-alias-button-primary-dimmed
  static const Color aliasButtonPrimaryDimmed = DeepSuiteStatic.neutralBluish100;
  /// --dsw-alias-button-primary-fill
  static const Color aliasButtonPrimaryFill = Color(0xff0f1115);
  /// --dsw-alias-button-primary-hover
  static const Color aliasButtonPrimaryHover = DeepSuiteStatic.neutralBluish750;
  /// --dsw-alias-button-tool-bar-fill
  static const Color aliasButtonToolBarFill = Color(0x80545557);
  /// --dsw-alias-button-tool-bar-fill-invisible
  static const Color aliasButtonToolBarFillInvisible = Color(0x5c1f1f1f);
  /// --dsw-alias-button-tool-bar-hover
  static const Color aliasButtonToolBarHover = Color(0x99545557);
  /// --dsw-alias-interactive-bg-active
  static const Color aliasInteractiveBgActive = Color(0x1a263148);
  /// --dsw-alias-interactive-bg-hover
  static const Color aliasInteractiveBgHover = Color(0x0f263148);
  /// --dsw-alias-interactive-bg-hover-accent
  static const Color aliasInteractiveBgHoverAccent = Color(0x24263148);
  /// --dsw-alias-interactive-bg-hover-danger
  static const Color aliasInteractiveBgHoverDanger = Color(0x0dec1313);
  /// --dsw-alias-interactive-bg-hover-solid
  static const Color aliasInteractiveBgHoverSolid = DeepSuiteStatic.neutralBluish75;
  /// --dsw-alias-label-caption
  static const Color aliasLabelCaption = DeepSuiteStatic.neutralBluish400;
  /// --dsw-alias-label-dimmed
  static const Color aliasLabelDimmed = DeepSuiteStatic.neutralBluish200;
  /// --dsw-alias-label-primary
  static const Color aliasLabelPrimary = DeepSuiteStatic.neutralBluish1000;
  /// --dsw-alias-label-primary-bluish
  static const Color aliasLabelPrimaryBluish = DeepSuiteStatic.blue900;
  /// --dsw-alias-label-primary-dimmed
  static const Color aliasLabelPrimaryDimmed = DeepSuiteStatic.neutralBluish950;
  /// --dsw-alias-label-primary-foreground
  static const Color aliasLabelPrimaryForeground = DeepSuiteStatic.neutralBluish00;
  /// --dsw-alias-label-primary-inverted
  static const Color aliasLabelPrimaryInverted = DeepSuiteStatic.neutralBluish00;
  /// --dsw-alias-label-secondary
  static const Color aliasLabelSecondary = DeepSuiteStatic.neutralBluish700;
  /// --dsw-alias-label-tertiary
  static const Color aliasLabelTertiary = DeepSuiteStatic.neutralBluish600;
  /// --dsw-alias-markdown-citation
  static const Color aliasMarkdownCitation = DeepSuiteStatic.neutralBluish100;
  /// --dsw-alias-markdown-code-block
  static const Color aliasMarkdownCodeBlock = DeepSuiteStatic.neutralBluish50;
  /// --dsw-alias-markdown-code-block-banner
  static const Color aliasMarkdownCodeBlockBanner = DeepSuiteStatic.neutralBluish50;
  /// --dsw-alias-markdown-code-segment-selected
  static const Color aliasMarkdownCodeSegmentSelected = DeepSuiteStatic.neutralBluish00;
  /// --dsw-alias-markdown-code-segment-unselected
  static const Color aliasMarkdownCodeSegmentUnselected = DeepSuiteStatic.neutralBluish75;
  /// --dsw-alias-markdown-inline-code
  static const Color aliasMarkdownInlineCode = DeepSuiteStatic.neutralBluish100;
  /// --dsw-alias-markdown-placeholder
  static const Color aliasMarkdownPlaceholder = Color(0xfff5f6f7);
  /// --dsw-alias-markdown-tag
  static const Color aliasMarkdownTag = DeepSuiteStatic.neutralBluish75;
  /// --dsw-alias-scrollbar-bg-l1
  static const Color aliasScrollbarBgL1 = DeepSuiteStatic.neutral200;
  /// --dsw-alias-scrollbar-bg-l2
  static const Color aliasScrollbarBgL2 = DeepSuiteStatic.neutral200;
  /// --dsw-alias-scrollbar-hover-l1
  static const Color aliasScrollbarHoverL1 = DeepSuiteStatic.neutral300;
  /// --dsw-alias-scrollbar-hover-l2
  static const Color aliasScrollbarHoverL2 = DeepSuiteStatic.neutral300;
  /// --dsw-alias-state-business-primary
  static const Color aliasStateBusinessPrimary = DeepSuiteStatic.deepseek500;
  /// --dsw-alias-state-business-tertiary
  static const Color aliasStateBusinessTertiary = DeepSuiteStatic.deepseek100;
  /// --dsw-alias-state-error-primary
  static const Color aliasStateErrorPrimary = DeepSuiteStatic.red600;
  /// --dsw-alias-state-error-secondary
  static const Color aliasStateErrorSecondary = DeepSuiteStatic.red400;
  /// --dsw-alias-state-success-primary
  static const Color aliasStateSuccessPrimary = DeepSuiteStatic.green500;
  /// --dsw-alias-state-success-secondary
  static const Color aliasStateSuccessSecondary = DeepSuiteStatic.green400;
  /// --dsw-alias-state-success-tertiary
  static const Color aliasStateSuccessTertiary = DeepSuiteStatic.green100;
  /// --dsw-alias-state-warn-label
  static const Color aliasStateWarnLabel = DeepSuiteStatic.amber600;
  /// --dsw-alias-state-warn-primary
  static const Color aliasStateWarnPrimary = DeepSuiteStatic.amber500;
  /// --dsw-alias-state-warn-secondary
  static const Color aliasStateWarnSecondary = DeepSuiteStatic.amber400;
  /// --dsw-alias-state-warn-tertiary
  static const Color aliasStateWarnTertiary = DeepSuiteStatic.amber100;
  /// --dsw-alias-toast-bg
  static const Color aliasToastBg = DeepSuiteStatic.neutralBluish800;
  /// --dsw-alias-tooltip-bg
  static const Color aliasTooltipBg = DeepSuiteStatic.neutralBluish850;
  /// --dsw-specific-bubble
  static const Color specificBubble = DeepSuiteStatic.deepseek50;
  /// --dsw-specific-bubble-highlight
  static const Color specificBubbleHighlight = DeepSuiteStatic.deepseek200;
  /// --dsw-specific-input-major
  static const Color specificInputMajor = DeepSuiteStatic.neutralBluish00;
  /// --dsw-specific-login-input
  static const Color specificLoginInput = DeepSuiteStatic.neutralBluish50;
  /// --dsw-specific-menu
  static const Color specificMenu = Color(0xffffffff);
  /// --dsw-specific-selector
  static const Color specificSelector = Color(0xfff5f6f7);
  /// --dsw-specific-sidebar-fill
  static const Color specificSidebarFill = DeepSuiteStatic.neutralBluish50;
  /// --dsw-specific-sidebar-nav-item-active
  static const Color specificSidebarNavItemActive = DeepSuiteStatic.neutralBluish100;
  /// --dsw-specific-sidebar-nav-item-active-accent
  static const Color specificSidebarNavItemActiveAccent = DeepSuiteStatic.deepseek100;
  /// --dsw-specific-sidebar-nav-item-hover
  static const Color specificSidebarNavItemHover = DeepSuiteStatic.neutralBluish75;
  /// --dsw-specific-tip
  static const Color specificTip = Color(0xfff5f6f7);
  /// Same tokens keyed by CSS name (parity tests, A2 consumers).
  static const Map<String, Color> byName = <String, Color>{
    "--dsw-alias-bg-base": aliasBgBase,
    "--dsw-alias-bg-layer-1": aliasBgLayer1,
    "--dsw-alias-bg-layer-2": aliasBgLayer2,
    "--dsw-alias-bg-layer-3": aliasBgLayer3,
    "--dsw-alias-bg-mask-1": aliasBgMask1,
    "--dsw-alias-bg-mask-2": aliasBgMask2,
    "--dsw-alias-bg-mask-3": aliasBgMask3,
    "--dsw-alias-bg-mask-drop": aliasBgMaskDrop,
    "--dsw-alias-bg-mask-photo": aliasBgMaskPhoto,
    "--dsw-alias-bg-module-platform": aliasBgModulePlatform,
    "--dsw-alias-bg-multi-select": aliasBgMultiSelect,
    "--dsw-alias-bg-overlay": aliasBgOverlay,
    "--dsw-alias-bg-skeleton": aliasBgSkeleton,
    "--dsw-alias-border-inverted": aliasBorderInverted,
    "--dsw-alias-border-inverted2": aliasBorderInverted2,
    "--dsw-alias-border-l1": aliasBorderL1,
    "--dsw-alias-border-l2": aliasBorderL2,
    "--dsw-alias-border-l2-darkmode-thin": aliasBorderL2DarkmodeThin,
    "--dsw-alias-border-l3": aliasBorderL3,
    "--dsw-alias-border-l4": aliasBorderL4,
    "--dsw-alias-brand-primary": aliasBrandPrimary,
    "--dsw-alias-brand-primary-invert": aliasBrandPrimaryInvert,
    "--dsw-alias-brand-primary-new-colorprimary-new-color": aliasBrandPrimaryNewColorprimaryNewColor,
    "--dsw-alias-brand-text": aliasBrandText,
    "--dsw-alias-button-contrast-fill": aliasButtonContrastFill,
    "--dsw-alias-button-elevated-fill": aliasButtonElevatedFill,
    "--dsw-alias-button-floating-fill": aliasButtonFloatingFill,
    "--dsw-alias-button-floating-hover": aliasButtonFloatingHover,
    "--dsw-alias-button-ghost-active-border": aliasButtonGhostActiveBorder,
    "--dsw-alias-button-ghost-active-fill": aliasButtonGhostActiveFill,
    "--dsw-alias-button-ghost-active-hover": aliasButtonGhostActiveHover,
    "--dsw-alias-button-info-fill": aliasButtonInfoFill,
    "--dsw-alias-button-info-hover": aliasButtonInfoHover,
    "--dsw-alias-button-primary-dimmed": aliasButtonPrimaryDimmed,
    "--dsw-alias-button-primary-fill": aliasButtonPrimaryFill,
    "--dsw-alias-button-primary-hover": aliasButtonPrimaryHover,
    "--dsw-alias-button-tool-bar-fill": aliasButtonToolBarFill,
    "--dsw-alias-button-tool-bar-fill-invisible": aliasButtonToolBarFillInvisible,
    "--dsw-alias-button-tool-bar-hover": aliasButtonToolBarHover,
    "--dsw-alias-interactive-bg-active": aliasInteractiveBgActive,
    "--dsw-alias-interactive-bg-hover": aliasInteractiveBgHover,
    "--dsw-alias-interactive-bg-hover-accent": aliasInteractiveBgHoverAccent,
    "--dsw-alias-interactive-bg-hover-danger": aliasInteractiveBgHoverDanger,
    "--dsw-alias-interactive-bg-hover-solid": aliasInteractiveBgHoverSolid,
    "--dsw-alias-label-caption": aliasLabelCaption,
    "--dsw-alias-label-dimmed": aliasLabelDimmed,
    "--dsw-alias-label-primary": aliasLabelPrimary,
    "--dsw-alias-label-primary-bluish": aliasLabelPrimaryBluish,
    "--dsw-alias-label-primary-dimmed": aliasLabelPrimaryDimmed,
    "--dsw-alias-label-primary-foreground": aliasLabelPrimaryForeground,
    "--dsw-alias-label-primary-inverted": aliasLabelPrimaryInverted,
    "--dsw-alias-label-secondary": aliasLabelSecondary,
    "--dsw-alias-label-tertiary": aliasLabelTertiary,
    "--dsw-alias-markdown-citation": aliasMarkdownCitation,
    "--dsw-alias-markdown-code-block": aliasMarkdownCodeBlock,
    "--dsw-alias-markdown-code-block-banner": aliasMarkdownCodeBlockBanner,
    "--dsw-alias-markdown-code-segment-selected": aliasMarkdownCodeSegmentSelected,
    "--dsw-alias-markdown-code-segment-unselected": aliasMarkdownCodeSegmentUnselected,
    "--dsw-alias-markdown-inline-code": aliasMarkdownInlineCode,
    "--dsw-alias-markdown-placeholder": aliasMarkdownPlaceholder,
    "--dsw-alias-markdown-tag": aliasMarkdownTag,
    "--dsw-alias-scrollbar-bg-l1": aliasScrollbarBgL1,
    "--dsw-alias-scrollbar-bg-l2": aliasScrollbarBgL2,
    "--dsw-alias-scrollbar-hover-l1": aliasScrollbarHoverL1,
    "--dsw-alias-scrollbar-hover-l2": aliasScrollbarHoverL2,
    "--dsw-alias-state-business-primary": aliasStateBusinessPrimary,
    "--dsw-alias-state-business-tertiary": aliasStateBusinessTertiary,
    "--dsw-alias-state-error-primary": aliasStateErrorPrimary,
    "--dsw-alias-state-error-secondary": aliasStateErrorSecondary,
    "--dsw-alias-state-success-primary": aliasStateSuccessPrimary,
    "--dsw-alias-state-success-secondary": aliasStateSuccessSecondary,
    "--dsw-alias-state-success-tertiary": aliasStateSuccessTertiary,
    "--dsw-alias-state-warn-label": aliasStateWarnLabel,
    "--dsw-alias-state-warn-primary": aliasStateWarnPrimary,
    "--dsw-alias-state-warn-secondary": aliasStateWarnSecondary,
    "--dsw-alias-state-warn-tertiary": aliasStateWarnTertiary,
    "--dsw-alias-toast-bg": aliasToastBg,
    "--dsw-alias-tooltip-bg": aliasTooltipBg,
    "--dsw-specific-bubble": specificBubble,
    "--dsw-specific-bubble-highlight": specificBubbleHighlight,
    "--dsw-specific-input-major": specificInputMajor,
    "--dsw-specific-login-input": specificLoginInput,
    "--dsw-specific-menu": specificMenu,
    "--dsw-specific-selector": specificSelector,
    "--dsw-specific-sidebar-fill": specificSidebarFill,
    "--dsw-specific-sidebar-nav-item-active": specificSidebarNavItemActive,
    "--dsw-specific-sidebar-nav-item-active-accent": specificSidebarNavItemActiveAccent,
    "--dsw-specific-sidebar-nav-item-hover": specificSidebarNavItemHover,
    "--dsw-specific-tip": specificTip,
  };
}

/// Semantic `Dark` aliases resolved to concrete colors.
final class DeepSuiteDark {
  const DeepSuiteDark._();
  /// --dsw-alias-bg-base
  static const Color aliasBgBase = DeepSuiteStatic.neutralBluish950;
  /// --dsw-alias-bg-layer-1
  static const Color aliasBgLayer1 = DeepSuiteStatic.neutralBluish875;
  /// --dsw-alias-bg-layer-2
  static const Color aliasBgLayer2 = DeepSuiteStatic.neutralBluish850;
  /// --dsw-alias-bg-layer-3
  static const Color aliasBgLayer3 = DeepSuiteStatic.neutralBluish800;
  /// --dsw-alias-bg-mask-1
  static const Color aliasBgMask1 = Color(0x80000000);
  /// --dsw-alias-bg-mask-2
  static const Color aliasBgMask2 = Color(0x33000000);
  /// --dsw-alias-bg-mask-3
  static const Color aliasBgMask3 = Color(0x7a000000);
  /// --dsw-alias-bg-mask-drop
  static const Color aliasBgMaskDrop = Color(0xb2272730);
  /// --dsw-alias-bg-mask-photo
  static const Color aliasBgMaskPhoto = Color(0xe0000000);
  /// --dsw-alias-bg-module-platform
  static const Color aliasBgModulePlatform = DeepSuiteStatic.neutralBluish800;
  /// --dsw-alias-bg-multi-select
  static const Color aliasBgMultiSelect = DeepSuiteStatic.neutral850;
  /// --dsw-alias-bg-overlay
  static const Color aliasBgOverlay = DeepSuiteStatic.neutralBluish700;
  /// --dsw-alias-bg-skeleton
  static const Color aliasBgSkeleton = Color(0x14ffffff);
  /// --dsw-alias-border-inverted
  static const Color aliasBorderInverted = Color(0x0fffffff);
  /// --dsw-alias-border-inverted2
  static const Color aliasBorderInverted2 = Color(0x14ffffff);
  /// --dsw-alias-border-l1
  static const Color aliasBorderL1 = Color(0x0fffffff);
  /// --dsw-alias-border-l2
  static const Color aliasBorderL2 = Color(0x1fffffff);
  /// --dsw-alias-border-l2-darkmode-thin
  static const Color aliasBorderL2DarkmodeThin = Color(0x0fffffff);
  /// --dsw-alias-border-l3
  static const Color aliasBorderL3 = Color(0x29ffffff);
  /// --dsw-alias-border-l4
  static const Color aliasBorderL4 = Color(0x33ffffff);
  /// --dsw-alias-brand-primary
  static const Color aliasBrandPrimary = DeepSuiteStatic.neutralBluish50;
  /// --dsw-alias-brand-primary-invert
  static const Color aliasBrandPrimaryInvert = DeepSuiteStatic.neutralBluish50;
  /// --dsw-alias-brand-primary-new-colorprimary-new-color
  static const Color aliasBrandPrimaryNewColorprimaryNewColor = DeepSuiteStatic.deepseek450;
  /// --dsw-alias-brand-text
  static const Color aliasBrandText = DeepSuiteStatic.neutralBluish50;
  /// --dsw-alias-button-contrast-fill
  static const Color aliasButtonContrastFill = DeepSuiteStatic.neutralBluish50;
  /// --dsw-alias-button-elevated-fill
  static const Color aliasButtonElevatedFill = DeepSuiteStatic.neutralBluish750;
  /// --dsw-alias-button-floating-fill
  static const Color aliasButtonFloatingFill = DeepSuiteStatic.neutralBluish850;
  /// --dsw-alias-button-floating-hover
  static const Color aliasButtonFloatingHover = DeepSuiteStatic.neutralBluish800;
  /// --dsw-alias-button-ghost-active-border
  static const Color aliasButtonGhostActiveBorder = DeepSuiteStatic.neutralBluish600;
  /// --dsw-alias-button-ghost-active-fill
  static const Color aliasButtonGhostActiveFill = DeepSuiteStatic.neutralBluish750;
  /// --dsw-alias-button-ghost-active-hover
  static const Color aliasButtonGhostActiveHover = DeepSuiteStatic.neutralBluish700;
  /// --dsw-alias-button-info-fill
  static const Color aliasButtonInfoFill = DeepSuiteStatic.deepseek400;
  /// --dsw-alias-button-info-hover
  static const Color aliasButtonInfoHover = DeepSuiteStatic.deepseek500;
  /// --dsw-alias-button-primary-dimmed
  static const Color aliasButtonPrimaryDimmed = DeepSuiteStatic.neutralBluish750;
  /// --dsw-alias-button-primary-fill
  static const Color aliasButtonPrimaryFill = Color(0xfff9fafb);
  /// --dsw-alias-button-primary-hover
  static const Color aliasButtonPrimaryHover = DeepSuiteStatic.neutralBluish100;
  /// --dsw-alias-button-tool-bar-fill
  static const Color aliasButtonToolBarFill = Color(0x80545557);
  /// --dsw-alias-button-tool-bar-fill-invisible
  static const Color aliasButtonToolBarFillInvisible = Color(0x5c1f1f1f);
  /// --dsw-alias-button-tool-bar-hover
  static const Color aliasButtonToolBarHover = Color(0x99545557);
  /// --dsw-alias-interactive-bg-active
  static const Color aliasInteractiveBgActive = Color(0x24ffffff);
  /// --dsw-alias-interactive-bg-hover
  static const Color aliasInteractiveBgHover = Color(0x14ffffff);
  /// --dsw-alias-interactive-bg-hover-accent
  static const Color aliasInteractiveBgHoverAccent = Color(0x3dffffff);
  /// --dsw-alias-interactive-bg-hover-danger
  static const Color aliasInteractiveBgHoverDanger = Color(0x26f25a5a);
  /// --dsw-alias-interactive-bg-hover-solid
  static const Color aliasInteractiveBgHoverSolid = DeepSuiteStatic.neutralBluish800;
  /// --dsw-alias-label-caption
  static const Color aliasLabelCaption = DeepSuiteStatic.neutralBluish600;
  /// --dsw-alias-label-dimmed
  static const Color aliasLabelDimmed = DeepSuiteStatic.neutralBluish750;
  /// --dsw-alias-label-primary
  static const Color aliasLabelPrimary = DeepSuiteStatic.neutralBluish50;
  /// --dsw-alias-label-primary-bluish
  static const Color aliasLabelPrimaryBluish = DeepSuiteStatic.neutralBluish50;
  /// --dsw-alias-label-primary-dimmed
  static const Color aliasLabelPrimaryDimmed = DeepSuiteStatic.neutralBluish100;
  /// --dsw-alias-label-primary-foreground
  static const Color aliasLabelPrimaryForeground = DeepSuiteStatic.neutralBluish1000;
  /// --dsw-alias-label-primary-inverted
  static const Color aliasLabelPrimaryInverted = DeepSuiteStatic.neutralBluish800;
  /// --dsw-alias-label-secondary
  static const Color aliasLabelSecondary = DeepSuiteStatic.neutralBluish300;
  /// --dsw-alias-label-tertiary
  static const Color aliasLabelTertiary = DeepSuiteStatic.neutralBluish400;
  /// --dsw-alias-markdown-citation
  static const Color aliasMarkdownCitation = DeepSuiteStatic.neutralBluish800;
  /// --dsw-alias-markdown-code-block
  static const Color aliasMarkdownCodeBlock = DeepSuiteStatic.neutralBluish900;
  /// --dsw-alias-markdown-code-block-banner
  static const Color aliasMarkdownCodeBlockBanner = DeepSuiteStatic.neutralBluish850;
  /// --dsw-alias-markdown-code-segment-selected
  static const Color aliasMarkdownCodeSegmentSelected = DeepSuiteStatic.neutralBluish800;
  /// --dsw-alias-markdown-code-segment-unselected
  static const Color aliasMarkdownCodeSegmentUnselected = DeepSuiteStatic.neutralBluish900;
  /// --dsw-alias-markdown-inline-code
  static const Color aliasMarkdownInlineCode = DeepSuiteStatic.neutralBluish850;
  /// --dsw-alias-markdown-placeholder
  static const Color aliasMarkdownPlaceholder = DeepSuiteStatic.neutralBluish850;
  /// --dsw-alias-markdown-tag
  static const Color aliasMarkdownTag = DeepSuiteStatic.neutralBluish850;
  /// --dsw-alias-scrollbar-bg-l1
  static const Color aliasScrollbarBgL1 = DeepSuiteStatic.neutral700;
  /// --dsw-alias-scrollbar-bg-l2
  static const Color aliasScrollbarBgL2 = DeepSuiteStatic.neutral600;
  /// --dsw-alias-scrollbar-hover-l1
  static const Color aliasScrollbarHoverL1 = DeepSuiteStatic.neutral600;
  /// --dsw-alias-scrollbar-hover-l2
  static const Color aliasScrollbarHoverL2 = DeepSuiteStatic.neutral550;
  /// --dsw-alias-state-business-primary
  static const Color aliasStateBusinessPrimary = DeepSuiteStatic.deepseek400;
  /// --dsw-alias-state-business-tertiary
  static const Color aliasStateBusinessTertiary = DeepSuiteStatic.deepseek800;
  /// --dsw-alias-state-error-primary
  static const Color aliasStateErrorPrimary = DeepSuiteStatic.red400;
  /// --dsw-alias-state-error-secondary
  static const Color aliasStateErrorSecondary = DeepSuiteStatic.red400;
  /// --dsw-alias-state-success-primary
  static const Color aliasStateSuccessPrimary = DeepSuiteStatic.green500;
  /// --dsw-alias-state-success-secondary
  static const Color aliasStateSuccessSecondary = DeepSuiteStatic.green400;
  /// --dsw-alias-state-success-tertiary
  static const Color aliasStateSuccessTertiary = DeepSuiteStatic.green900;
  /// --dsw-alias-state-warn-label
  static const Color aliasStateWarnLabel = DeepSuiteStatic.amber600;
  /// --dsw-alias-state-warn-primary
  static const Color aliasStateWarnPrimary = DeepSuiteStatic.amber500;
  /// --dsw-alias-state-warn-secondary
  static const Color aliasStateWarnSecondary = DeepSuiteStatic.amber400;
  /// --dsw-alias-state-warn-tertiary
  static const Color aliasStateWarnTertiary = DeepSuiteStatic.amber900;
  /// --dsw-alias-toast-bg
  static const Color aliasToastBg = DeepSuiteStatic.neutralBluish750;
  /// --dsw-alias-tooltip-bg
  static const Color aliasTooltipBg = DeepSuiteStatic.neutralBluish750;
  /// --dsw-specific-bubble
  static const Color specificBubble = DeepSuiteStatic.neutralBluish850;
  /// --dsw-specific-bubble-highlight
  static const Color specificBubbleHighlight = DeepSuiteStatic.neutralBluish750;
  /// --dsw-specific-input-major
  static const Color specificInputMajor = DeepSuiteStatic.neutralBluish850;
  /// --dsw-specific-login-input
  static const Color specificLoginInput = DeepSuiteStatic.neutralBluish900;
  /// --dsw-specific-menu
  static const Color specificMenu = Color(0xff353638);
  /// --dsw-specific-selector
  static const Color specificSelector = DeepSuiteStatic.neutralBluish800;
  /// --dsw-specific-sidebar-fill
  static const Color specificSidebarFill = DeepSuiteStatic.neutralBluish900;
  /// --dsw-specific-sidebar-nav-item-active
  static const Color specificSidebarNavItemActive = DeepSuiteStatic.neutralBluish750;
  /// --dsw-specific-sidebar-nav-item-active-accent
  static const Color specificSidebarNavItemActiveAccent = DeepSuiteStatic.neutralBluish800;
  /// --dsw-specific-sidebar-nav-item-hover
  static const Color specificSidebarNavItemHover = DeepSuiteStatic.neutralBluish850;
  /// --dsw-specific-tip
  static const Color specificTip = DeepSuiteStatic.neutralBluish800;
  /// Same tokens keyed by CSS name (parity tests, A2 consumers).
  static const Map<String, Color> byName = <String, Color>{
    "--dsw-alias-bg-base": aliasBgBase,
    "--dsw-alias-bg-layer-1": aliasBgLayer1,
    "--dsw-alias-bg-layer-2": aliasBgLayer2,
    "--dsw-alias-bg-layer-3": aliasBgLayer3,
    "--dsw-alias-bg-mask-1": aliasBgMask1,
    "--dsw-alias-bg-mask-2": aliasBgMask2,
    "--dsw-alias-bg-mask-3": aliasBgMask3,
    "--dsw-alias-bg-mask-drop": aliasBgMaskDrop,
    "--dsw-alias-bg-mask-photo": aliasBgMaskPhoto,
    "--dsw-alias-bg-module-platform": aliasBgModulePlatform,
    "--dsw-alias-bg-multi-select": aliasBgMultiSelect,
    "--dsw-alias-bg-overlay": aliasBgOverlay,
    "--dsw-alias-bg-skeleton": aliasBgSkeleton,
    "--dsw-alias-border-inverted": aliasBorderInverted,
    "--dsw-alias-border-inverted2": aliasBorderInverted2,
    "--dsw-alias-border-l1": aliasBorderL1,
    "--dsw-alias-border-l2": aliasBorderL2,
    "--dsw-alias-border-l2-darkmode-thin": aliasBorderL2DarkmodeThin,
    "--dsw-alias-border-l3": aliasBorderL3,
    "--dsw-alias-border-l4": aliasBorderL4,
    "--dsw-alias-brand-primary": aliasBrandPrimary,
    "--dsw-alias-brand-primary-invert": aliasBrandPrimaryInvert,
    "--dsw-alias-brand-primary-new-colorprimary-new-color": aliasBrandPrimaryNewColorprimaryNewColor,
    "--dsw-alias-brand-text": aliasBrandText,
    "--dsw-alias-button-contrast-fill": aliasButtonContrastFill,
    "--dsw-alias-button-elevated-fill": aliasButtonElevatedFill,
    "--dsw-alias-button-floating-fill": aliasButtonFloatingFill,
    "--dsw-alias-button-floating-hover": aliasButtonFloatingHover,
    "--dsw-alias-button-ghost-active-border": aliasButtonGhostActiveBorder,
    "--dsw-alias-button-ghost-active-fill": aliasButtonGhostActiveFill,
    "--dsw-alias-button-ghost-active-hover": aliasButtonGhostActiveHover,
    "--dsw-alias-button-info-fill": aliasButtonInfoFill,
    "--dsw-alias-button-info-hover": aliasButtonInfoHover,
    "--dsw-alias-button-primary-dimmed": aliasButtonPrimaryDimmed,
    "--dsw-alias-button-primary-fill": aliasButtonPrimaryFill,
    "--dsw-alias-button-primary-hover": aliasButtonPrimaryHover,
    "--dsw-alias-button-tool-bar-fill": aliasButtonToolBarFill,
    "--dsw-alias-button-tool-bar-fill-invisible": aliasButtonToolBarFillInvisible,
    "--dsw-alias-button-tool-bar-hover": aliasButtonToolBarHover,
    "--dsw-alias-interactive-bg-active": aliasInteractiveBgActive,
    "--dsw-alias-interactive-bg-hover": aliasInteractiveBgHover,
    "--dsw-alias-interactive-bg-hover-accent": aliasInteractiveBgHoverAccent,
    "--dsw-alias-interactive-bg-hover-danger": aliasInteractiveBgHoverDanger,
    "--dsw-alias-interactive-bg-hover-solid": aliasInteractiveBgHoverSolid,
    "--dsw-alias-label-caption": aliasLabelCaption,
    "--dsw-alias-label-dimmed": aliasLabelDimmed,
    "--dsw-alias-label-primary": aliasLabelPrimary,
    "--dsw-alias-label-primary-bluish": aliasLabelPrimaryBluish,
    "--dsw-alias-label-primary-dimmed": aliasLabelPrimaryDimmed,
    "--dsw-alias-label-primary-foreground": aliasLabelPrimaryForeground,
    "--dsw-alias-label-primary-inverted": aliasLabelPrimaryInverted,
    "--dsw-alias-label-secondary": aliasLabelSecondary,
    "--dsw-alias-label-tertiary": aliasLabelTertiary,
    "--dsw-alias-markdown-citation": aliasMarkdownCitation,
    "--dsw-alias-markdown-code-block": aliasMarkdownCodeBlock,
    "--dsw-alias-markdown-code-block-banner": aliasMarkdownCodeBlockBanner,
    "--dsw-alias-markdown-code-segment-selected": aliasMarkdownCodeSegmentSelected,
    "--dsw-alias-markdown-code-segment-unselected": aliasMarkdownCodeSegmentUnselected,
    "--dsw-alias-markdown-inline-code": aliasMarkdownInlineCode,
    "--dsw-alias-markdown-placeholder": aliasMarkdownPlaceholder,
    "--dsw-alias-markdown-tag": aliasMarkdownTag,
    "--dsw-alias-scrollbar-bg-l1": aliasScrollbarBgL1,
    "--dsw-alias-scrollbar-bg-l2": aliasScrollbarBgL2,
    "--dsw-alias-scrollbar-hover-l1": aliasScrollbarHoverL1,
    "--dsw-alias-scrollbar-hover-l2": aliasScrollbarHoverL2,
    "--dsw-alias-state-business-primary": aliasStateBusinessPrimary,
    "--dsw-alias-state-business-tertiary": aliasStateBusinessTertiary,
    "--dsw-alias-state-error-primary": aliasStateErrorPrimary,
    "--dsw-alias-state-error-secondary": aliasStateErrorSecondary,
    "--dsw-alias-state-success-primary": aliasStateSuccessPrimary,
    "--dsw-alias-state-success-secondary": aliasStateSuccessSecondary,
    "--dsw-alias-state-success-tertiary": aliasStateSuccessTertiary,
    "--dsw-alias-state-warn-label": aliasStateWarnLabel,
    "--dsw-alias-state-warn-primary": aliasStateWarnPrimary,
    "--dsw-alias-state-warn-secondary": aliasStateWarnSecondary,
    "--dsw-alias-state-warn-tertiary": aliasStateWarnTertiary,
    "--dsw-alias-toast-bg": aliasToastBg,
    "--dsw-alias-tooltip-bg": aliasTooltipBg,
    "--dsw-specific-bubble": specificBubble,
    "--dsw-specific-bubble-highlight": specificBubbleHighlight,
    "--dsw-specific-input-major": specificInputMajor,
    "--dsw-specific-login-input": specificLoginInput,
    "--dsw-specific-menu": specificMenu,
    "--dsw-specific-selector": specificSelector,
    "--dsw-specific-sidebar-fill": specificSidebarFill,
    "--dsw-specific-sidebar-nav-item-active": specificSidebarNavItemActive,
    "--dsw-specific-sidebar-nav-item-active-accent": specificSidebarNavItemActiveAccent,
    "--dsw-specific-sidebar-nav-item-hover": specificSidebarNavItemHover,
    "--dsw-specific-tip": specificTip,
  };
}

/// Alias keys in declaration order (light/dark parity test).
const List<String> kDeepSuiteAliasKeys = [
  "--dsw-alias-bg-base",
  "--dsw-alias-bg-layer-1",
  "--dsw-alias-bg-layer-2",
  "--dsw-alias-bg-layer-3",
  "--dsw-alias-bg-mask-1",
  "--dsw-alias-bg-mask-2",
  "--dsw-alias-bg-mask-3",
  "--dsw-alias-bg-mask-drop",
  "--dsw-alias-bg-mask-photo",
  "--dsw-alias-bg-module-platform",
  "--dsw-alias-bg-multi-select",
  "--dsw-alias-bg-overlay",
  "--dsw-alias-bg-skeleton",
  "--dsw-alias-border-inverted",
  "--dsw-alias-border-inverted2",
  "--dsw-alias-border-l1",
  "--dsw-alias-border-l2",
  "--dsw-alias-border-l2-darkmode-thin",
  "--dsw-alias-border-l3",
  "--dsw-alias-border-l4",
  "--dsw-alias-brand-primary",
  "--dsw-alias-brand-primary-invert",
  "--dsw-alias-brand-primary-new-colorprimary-new-color",
  "--dsw-alias-brand-text",
  "--dsw-alias-button-contrast-fill",
  "--dsw-alias-button-elevated-fill",
  "--dsw-alias-button-floating-fill",
  "--dsw-alias-button-floating-hover",
  "--dsw-alias-button-ghost-active-border",
  "--dsw-alias-button-ghost-active-fill",
  "--dsw-alias-button-ghost-active-hover",
  "--dsw-alias-button-info-fill",
  "--dsw-alias-button-info-hover",
  "--dsw-alias-button-primary-dimmed",
  "--dsw-alias-button-primary-fill",
  "--dsw-alias-button-primary-hover",
  "--dsw-alias-button-tool-bar-fill",
  "--dsw-alias-button-tool-bar-fill-invisible",
  "--dsw-alias-button-tool-bar-hover",
  "--dsw-alias-interactive-bg-active",
  "--dsw-alias-interactive-bg-hover",
  "--dsw-alias-interactive-bg-hover-accent",
  "--dsw-alias-interactive-bg-hover-danger",
  "--dsw-alias-interactive-bg-hover-solid",
  "--dsw-alias-label-caption",
  "--dsw-alias-label-dimmed",
  "--dsw-alias-label-primary",
  "--dsw-alias-label-primary-bluish",
  "--dsw-alias-label-primary-dimmed",
  "--dsw-alias-label-primary-foreground",
  "--dsw-alias-label-primary-inverted",
  "--dsw-alias-label-secondary",
  "--dsw-alias-label-tertiary",
  "--dsw-alias-markdown-citation",
  "--dsw-alias-markdown-code-block",
  "--dsw-alias-markdown-code-block-banner",
  "--dsw-alias-markdown-code-segment-selected",
  "--dsw-alias-markdown-code-segment-unselected",
  "--dsw-alias-markdown-inline-code",
  "--dsw-alias-markdown-placeholder",
  "--dsw-alias-markdown-tag",
  "--dsw-alias-scrollbar-bg-l1",
  "--dsw-alias-scrollbar-bg-l2",
  "--dsw-alias-scrollbar-hover-l1",
  "--dsw-alias-scrollbar-hover-l2",
  "--dsw-alias-state-business-primary",
  "--dsw-alias-state-business-tertiary",
  "--dsw-alias-state-error-primary",
  "--dsw-alias-state-error-secondary",
  "--dsw-alias-state-success-primary",
  "--dsw-alias-state-success-secondary",
  "--dsw-alias-state-success-tertiary",
  "--dsw-alias-state-warn-label",
  "--dsw-alias-state-warn-primary",
  "--dsw-alias-state-warn-secondary",
  "--dsw-alias-state-warn-tertiary",
  "--dsw-alias-toast-bg",
  "--dsw-alias-tooltip-bg",
  "--dsw-specific-bubble",
  "--dsw-specific-bubble-highlight",
  "--dsw-specific-input-major",
  "--dsw-specific-login-input",
  "--dsw-specific-menu",
  "--dsw-specific-selector",
  "--dsw-specific-sidebar-fill",
  "--dsw-specific-sidebar-nav-item-active",
  "--dsw-specific-sidebar-nav-item-active-accent",
  "--dsw-specific-sidebar-nav-item-hover",
  "--dsw-specific-tip",
];

// Motion + font tokens from ui-theme/src/styles/base.css.
const Duration kDsDurationFast = Duration(milliseconds: 100);
const Duration kDsDuration = Duration(milliseconds: 200);
const Duration kDsDurationSlow = Duration(milliseconds: 300);
// cubic-bezier(0.4, 0, 0.2, 1) maps onto Flutter Curves.easeInOut.
